name: CI

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Node
      uses: actions/setup-node@v1.1.0
      with:
        node-version: '13.6.0'
    - run: |
        cd server
        npm install
        npm run build
        cd ../website
        npm install
        npm run build
        mv build/ ../server/dist/
        cd ../server
        cd dist
        ls
        
       
        
        
